### PR TITLE
Fix PHP 5.0/5.1 compatibility

### PR DESCRIPTION
**Pull request by dryabov**
Use `preg_match` instead of `filter_var` to support PHP 5.0+
(see https://github.com/PhilETaylor/Joomla1.5.999/commit/95741d8a2bbb92ea3c8aeaa5427fec757e0c6895)

### CODE REVIEW

**Comment by mbabker** [comment]
Joomla 1.5 supported PHP 4.3.10+, dare I suggest that someone ensure PHP 4 is supported?

**Comment by PhilETaylor** [comment]
/me runs and hides under the table and rocks back and forward crying...

**Comment by passierschein-a38** [comment]
I have a Customer running php 4 and joomla 1.5, i have to apply the Patch
theese days.  I will adapt the code If needed.

Axel
Am 15.12.2015 08:11 schrieb "Phil Taylor" notifications@github.com:

**Comment by passierschein-a38** [comment]
sorry @all for my late response, my customer recently  updated his lampp to php 5 so I cannot provide any feedback to php4

**Pull request merged**
